/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopForm: typeof import('./src/components/TopForm.vue')['default']
    TopItem: typeof import('./src/components/TopItem.vue')['default']
    TopList: typeof import('./src/components/TopList.vue')['default']
  }
}
